      PROGRAM TIGHTBING
      USE prec; USE TB_MODULE
      IMPLICIT NONE
      INTEGER NA1MAX,NIONSL,NIS,NI,NBASE,IK
      INTEGER,PARAMETER::IU=14,IO=7
      COMPLEX(gq),ALLOCATABLE::C2N(:,:,:)
      INTEGER,ALLOCATABLE::NE(:,:)

      OPEN(7,FILE='log',STATUS='REPLACE')
      CALL VERSION()
      WRITE(*,*)'INI_TB...'
      CALL INI_TB(IU,IO)
      CALL GMPI_WRT()
      CALL GUTZ1_WRT(T_INFO%NIONS)
      CALL GUTZ2_WRT(1,W%ISPIN,QB%DIM,KPOINTS%NKPTS)
      CALL GUTZ3_WRT()
      NA1MAX=MAXVAL(TYZ(:)%QO%CDIM)
      ALLOCATE(C2N(NA1MAX,NA1MAX,T_INFO%NIONSL)); C2N=0
      NIS=0
      DO NI=1,T_INFO%NIONS
      IF(TYZ(NI)%QO%CRNG(2).LT.TYZ(NI)%QO%CRNG(1))CYCLE
      NIS=NIS+1
      C2N(1:TYZ(NI)%QO%CDIM,1:TYZ(NI)%QO%CDIM,NIS)=TYZ(NI)%QO%HAO(:,:,1)
      ENDDO
      CALL GUTZ4_WRT(C2N,NA1MAX,T_INFO%NIONSL)
      ALLOCATE(NE(3,KPOINTS%NKPTS))
      NE(1,:)=QB%DIM; NE(2,:)=1; NE(3,:)=QB%DIM
      CALL GUTZ5_WRT(KPOINTS%NKPTS,KPOINTS%WTKPT,W%NET,NE,'GAUSS',.01_gq)
      CALL CALC_FULL_BAND()
      OPEN(IU,FILE='BNDU_0.INP',STATUS='REPLACE',FORM="UNFORMATTED",ACCESS="SEQUENTIAL")
      DO IK=1,KPOINTS%NKPTS
        WRITE(IU)W%CELEN(:,IK,1)
        NIS=0; NBASE=0
        DO NI=1,T_INFO%NIONS
        IF(TYZ(NI)%QO%CRNG(2).LT.TYZ(NI)%QO%CRNG(1))GOTO 200
        NIS=NIS+1
        WRITE(IU)CONJG(TRANSPOSE(W%CPTWFP(NBASE+TYZ(NI)%QO%CRNG(1):NBASE+TYZ(NI)%QO%CRNG(2),:,IK,1)))
200     CONTINUE
        NBASE=NBASE+TYZ(NI)%QO%DIM
        ENDDO
      ENDDO
      CLOSE(IU)
      CALL SET_FERMI_WT(IO)
      CLOSE(IO)

      END PROGRAM TIGHTBING

!++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
      SUBROUTINE VERSION()
      USE prec
      IMPLICIT NONE
      CHARACTER DATE*8,TIME*10

      WRITE(7,'("************************************")')
      WRITE(7,'(" Tight-binding code 2009.9 by Y.Yao ")')
      WRITE(7,'("************************************")')
      CALL DATE_AND_TIME(date, time)
      WRITE(7,'(" Current date and time:",A8,":",A10)')DATE,TIME

      END SUBROUTINE VERSION
