#!/bin/csh -f 
#
unalias rm

set name  = $0
set name  = $name:t 		#name of this script-file
set file = `pwd`
set file    = $file:t		#tail of file-names
#---> path- and file-names
#
  unset recursive
  unset continue
  set silent
top:
if ( "$1" == '-r' )  then
  set recursive
  shift
endif
if ( "$1" == '-s' )  then
  set silent='-s'
  set continue
  shift
  goto top
endif
if ($1 == '-h')  goto help

if ($?recursive) then
  set dirlist=`/bin/ls -p |grep / `
  foreach i1 ($dirlist)
    cd $i1
    foreach  i2 (`/bin/ls -p |grep / ` )
      cd $i2
      foreach  i3 (`/bin/ls -p |grep / ` )
        cd $i3
        foreach  i4 (`/bin/ls -p |grep / ` )
          cd $i4
          foreach  i5 (`/bin/ls -p |grep / ` )
            cd $i5
            foreach  i6 (`/bin/ls -p |grep / ` )
              cd $i6
              foreach  i7 (`/bin/ls -p |grep / ` )
                cd $i7
                clean_lapw $silent
                cd ..
              end
              clean_lapw $silent
              cd ..
            end
            clean_lapw $silent
            cd ..
          end
          clean_lapw $silent
          cd ..
        end
        clean_lapw $silent
        cd ..
      end
      clean_lapw $silent
      cd ..
    end
    clean_lapw $silent
    cd ..
  end
endif
if($?continue) goto continue
  echo 'deletes all large (unnecessary) files! Do you want to continue [y/n] '
  set b=($<)
  if ($b != 'y')  exit(1)
#
continue:
echo "cleaning `pwd ` "
(ls $file.vec* $file.help* $file.vrespva* $file.vrespco* $file.clmval_* $file.clmvalup_* $file.clmvaldn_* $file.output0[1-9]0[0-9] $file.output00[1-9][0-9] $file.output0[1-9][1-9][0-9] $file.output1_*_proc* $file.output1up_*_proc* $file.*.e* $file.*.o* $file.output1dn_*_proc* $file.output2_* $file.output2up_* $file.output2dn_* $file.recprlist $file.scfdm_* $file.scfdmup_* $file.scfdmdn_* $file.dmat_[0-9]* $file.dmatup_[0-9]* $file.dmatdn_[0-9]* $file.dmatud_[0-9]* BNDU* KSWT* GL*TMP> cleanfilelist1 )>& /dev/null
set a=`cat cleanfilelist1`
(ls $file.storeHinv* $file.nsh* $file.vint* $file.storeHinv* $file.nval* $file.broy* $file.*_old *~ $file.corew* fort.* ftn* *.error > cleanfilelist2 )>& /dev/null
set a1=`cat cleanfilelist2`
(ls .command* .running* .lapw?para .time?_* .tmp? :parallel* This_file* .processes .script .mist* .time_* :log STDOUT $file.klist_[0-9]* $file.weigh* .in.tmp* *.scf1*_* *.scf2*_* *.tmp* > cleanfilelist3 )>& /dev/null
set a2=`cat cleanfilelist3`
rm cleanfilelist*
if ( "$silent" == '-s') then
  foreach i ($a $a1 $a2)
  rm $i
  end
  exit (0) 
else
  foreach i ($a $a1 $a2)
  ls $i		
  rm $i
  end
  echo ' all large (unnecessary) files deleted\! ' 
  exit (0)
endif

help:
cat << theend 

PROGRAM:	$0

PURPOSE:	cleaning of a case subdirectory of WIEN95
		to be called within the case-directory
		deletes all files which are not necessary for continuation

USAGE:		$name  [-s -r]

FLAGS:
-h ->		help
-s ->           silent operation
-r ->           recursive in all subdirectories (7 levels deep)
theend

exit(1)
 
